name: 'downloader'
repository: github.com/afdesk/downloader
version: '0.0.3'
usage: download vulnerability databases
description: |-
    simplify the downloading of vulnerability database and Java index database.
platforms:
    - selector:
          os: linux
          arch: amd64
      uri: https://github.com/afdesk/downloader/releases/download/v0.0.3/downloader.tar.gz
      bin: ./downloader
    - selector: # dev
          os: darwin
          arch: arm64
      uri: ./downloader
      bin: ./downloader
