name: Release

on:
    push:
        branches:
            - 'main'
        paths:
            - 'plugin.yaml'

permissions:
    contents: write

jobs:
    check-version:
        uses: afdesk/trivy-go-plugin/.github/workflows/check-version.yaml@main

    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs: check-version
        if: ${{ needs.check-version.outputs.next_version != '' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Compress
              id: compress
              run: tar -czvf downloader.tar.gz LICENSE downloader
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: downloader.tar.gz
                  tag_name: v${{ needs.check-version.outputs.next_version }}
